name: Node.js Package

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: npm publish packages/sharing-validator
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
